###create a new Relation
POST http://localhost:4000/relationship/users
content-type: application/json

{
    "recepient": 4,
    "status": "pending"
}

### Get all Relation
GET http://localhost:4000/relationship?status=friend

### update the status of relationship
PATCH http://localhost:4000/relationship/update
content-type: application/json

{
    "recepient": 2,
    "status": "blocked"
}

### Delete all (CAUTION: THIS WILL DELETE EVERY RELATION)
DELETE http://localhost:4000/relationship/all